//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.pci.forms.terminationdetailsdialog;

public abstract class BaseLogic extends Handlers
{
	public final Class getDomainInterface() throws ClassNotFoundException
	{
		return ims.domain.DomainInterface.class;
	}
	public final void setContext(ims.framework.UIEngine engine, GenForm form, ims.domain.DomainInterface domain)
	{
		setContext(engine, form);
		this.domain = domain;
	}
	protected final void oncmbTerminationReasonValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.cmbTerminationReason().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.pci.vo.lookups.TerminationReason existingInstance = (ims.pci.vo.lookups.TerminationReason)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbTerminationReasonLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.pci.vo.lookups.TerminationReason)
		{
			ims.pci.vo.lookups.TerminationReason instance = (ims.pci.vo.lookups.TerminationReason)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbTerminationReasonLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.pci.vo.lookups.TerminationReason existingInstance = (ims.pci.vo.lookups.TerminationReason)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.cmbTerminationReason().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbTerminationReasonLookup()
	{
		this.form.cmbTerminationReason().clear();
		ims.pci.vo.lookups.TerminationReasonCollection lookupCollection = ims.pci.vo.lookups.LookupHelper.getTerminationReason(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.cmbTerminationReason().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbTerminationReasonLookupValue(int id)
	{
		ims.pci.vo.lookups.TerminationReason instance = ims.pci.vo.lookups.LookupHelper.getTerminationReasonInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.cmbTerminationReason().setValue(instance);
	}
	protected final void defaultcmbTerminationReasonLookupValue()
	{
		this.form.cmbTerminationReason().setValue((ims.pci.vo.lookups.TerminationReason)domain.getLookupService().getDefaultInstance(ims.pci.vo.lookups.TerminationReason.class, engine.getFormName().getID(), ims.pci.vo.lookups.TerminationReason.TYPE_ID));
	}
	public void initialize() throws ims.framework.exceptions.FormOpenException
	{
	}
	public boolean allowNew()
	{
		return form.getMode() == ims.framework.enumerations.FormMode.VIEW && !form.isReadOnly();
	}
	public boolean allowUpdate()
	{
		return form.getMode() == ims.framework.enumerations.FormMode.VIEW && !form.isReadOnly();
	}
	public String[] validateUIRules()
	{
		return null;
	}
	public void clear()
	{
	}
	public void search()
	{
	}
	public final void free()
	{
		super.free();
		domain = null;
	}
	
	protected ims.domain.DomainInterface domain;
}
