//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.correspondence.domain.base.impl;

import ims.domain.impl.DomainImpl;

public abstract class BaseTemplateAssociationsConfigurationImpl extends DomainImpl implements ims.correspondence.domain.TemplateAssociationsConfiguration, ims.domain.impl.Transactional
{
	private static final long serialVersionUID = 1L;

	@SuppressWarnings("unused")
	public void validatelistTemplatesByName(String templateName)
	{
	}

	@SuppressWarnings("unused")
	public void validategetTemplateAssociation(ims.core.admin.vo.TemplateBoRefVo template)
	{
	}

	@SuppressWarnings("unused")
	public void validatelistClinics(ims.core.vo.ClinicLiteVo filterVo)
	{
		if(filterVo == null)
			throw new ims.domain.exceptions.DomainRuntimeException("The parameter 'filterVo' of type 'ims.core.vo.ClinicLiteVo' cannot be null.");
	}

	@SuppressWarnings("unused")
	public void validatelistConsultants(ims.core.vo.MedicLiteVo filterVo)
	{
		if(filterVo == null)
			throw new ims.domain.exceptions.DomainRuntimeException("The parameter 'filterVo' of type 'ims.core.vo.MedicLiteVo' cannot be null.");
	}

	@SuppressWarnings("unused")
	public void validatelistSpecialties(ims.core.vo.lookups.Specialty filterLookup)
	{
		if(filterLookup == null)
			throw new ims.domain.exceptions.DomainRuntimeException("The parameter 'filterLookup' of type 'ims.core.vo.lookups.Specialty' cannot be null.");
	}

	@SuppressWarnings("unused")
	public void validatesaveTemplateAssociations(ims.correspondence.vo.TemplateAssociationsVo templateAssociation)
	{
		if(templateAssociation == null)
			throw new ims.domain.exceptions.DomainRuntimeException("The parameter 'templateAssociation' of type 'ims.correspondence.vo.TemplateAssociationsVo' cannot be null.");
	}
}
