//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Cornel Ventuneac using IMS Development Environment (version 1.80 build 4261.20360)
// Copyright (C) 1995-2011 IMS MAXIMS. All rights reserved.

package ims.core.forms.patientdetails;

import java.util.ArrayList;

import ims.configuration.AppRight;
import ims.configuration.gen.ConfigFlag;
import ims.core.vo.DemographicControlsConfigVo;
import ims.core.vo.DemographicControlsConfigVoCollection;
import ims.core.vo.Patient;
import ims.core.vo.PatientDetailsComponentVo;
import ims.core.vo.PatientFilter;
import ims.core.vo.lookups.NameType;
import ims.core.vo.lookups.OccupationCollection;
import ims.domain.exceptions.DomainInterfaceException;
import ims.framework.enumerations.FormMode;
import ims.framework.exceptions.PresentationLogicException;
import ims.framework.utils.Date;
import ims.framework.utils.Image;
import ims.framework.utils.Time;


public class Logic extends BaseLogic
{
	private static final long serialVersionUID = 1L;
	
	
	private static final Integer NONE = new Integer(0);
	private static final Integer BUTTON_OTHERNAMES = new Integer(1);
	private static final Integer BUTTON_ALIAS = new Integer(2);
	private static final Integer BUTTON_DECEASED = new Integer(3);
	
	//wdev-19528
	private static final String TITLE_DEMOGR 			= "DEM01";
	private static final String FORENAME_DEMOGR 		= "DEM02";
	private static final String MIDDLENAME_DEMOGR 		= "DEM03";
	private static final String SURNAME_DEMOGR 			= "DEM04";
	private static final String SEX_DEMOGR 				= "DEM05";
	private static final String DOB_DEMOGR 				= "DEM06";
	private static final String MARITAL_STATUS_DEMOGR	= "DEM07";
	private static final String OCCUPATION_DEMOGR 		= "DEM08";
	private static final String RELIGION_DEMOGR 		= "DEM09";
	private static final String ETHNIC_ORIGIN_DEMOGR	= "DEM10";
	//------------------------------------------------------------

	
	protected void onFormOpen(Object[] args) throws ims.framework.exceptions.PresentationLogicException
	{
		form.txtSurname().setRequired(true);	//wdev-19528
		form.getLocalContext().setButtonAction(NONE);
		if (ConfigFlag.UI.DEMOGRAPHICS_TYPE.getValue().equals("UK"))
		{
			form.lblEthnicOrigin().setVisible(true);
			form.lblEthnicOrigin2().setVisible(true);
			form.cmbEthnic().setVisible(true);
			form.cmbEthnic().setEnabled(false);
			form.qmbOccupation().setVisible(false);
			form.lblOccupation().setVisible(false);
			
		}
		else if (ConfigFlag.UI.DEMOGRAPHICS_TYPE.getValue().equals("IRISH"))
		{
			
			form.lblEthnicOrigin().setVisible(false);
			form.lblEthnicOrigin2().setVisible(false);
			form.cmbEthnic().setVisible(false);
			form.qmbOccupation().setEnabled(false);
		}
		
		form.txtForename().setRequired(ConfigFlag.DOM.FORENAME1_IS_MANDATORY.getValue());//WDEV-12962
		form.btnDeceased().setVisible(false);//wdev-12966
		form.cmbSex().setRequired(ConfigFlag.DOM.GENDER_IS_MANDATORY_FOR_REGISTRATION.getValue());	//WDEV-12972
		
		//wdev-13000
		
		form.imbAlias().setVisible(ConfigFlag.DOM.USE_ALIAS_SURNAME_FUNCTIONALITY.getValue());
		
		form.getLocalContext().setDemographicDetailsCannotBeEdited(null);		//wdev-15845
		
		

	}
	
	protected void onImbAliasClick() throws ims.framework.exceptions.PresentationLogicException
	{
		
		//0- none, 1-imbOtherNames, 2 - imbAlias, 3 - btnDeceased
		setButtonAction(BUTTON_ALIAS);
		form.fireCustomControlValueChanged();
		
	}
	
	protected void onBtnDeceasedClick() throws ims.framework.exceptions.PresentationLogicException
	{
		//0- none, 1-imbOtherNames, 2 - imbAlias, 3 - btnDeceased
		setButtonAction(BUTTON_DECEASED);
		form.fireCustomControlValueChanged();
	}
	
	protected void onImbOtherNamesClick() throws ims.framework.exceptions.PresentationLogicException
	{
		//0- none, 1-imbOtherNames, 2 - imbAlias, 3 - btnDeceased
		setButtonAction(BUTTON_OTHERNAMES);
		form.fireCustomControlValueChanged();
	}
	public void setVisiblelblEthnicOrigin(Boolean visibleB)
	{
		// TODO: Add your code here.
	}

	public void setcmbEthnicVisble(Boolean isVisible)
	{
		form.cmbEthnic().setVisible(isVisible);
	}

	public void setcmbEthnicEnabled(Boolean enable)
	{
		form.cmbEthnic().setEnabled(enable);
	}

	public void setcmbOccupationVisible(Boolean visible)
	{
		form.qmbOccupation().setVisible(visible);
	}

	public void setlblOccupationVisible(Boolean visible)
	{
		form.lblOccupation().setVisible(visible);
	}

	public void setcmbOccupationEnabled(Boolean enabled)
	{
		form.qmbOccupation().setEnabled(enabled);
	}

	public void setIsRequiredtxtForename(Boolean required)
	{
		// TODO: Add your code here.
	}

	public void setcmbSexIsRequire(Boolean required)
	{
		// TODO: Add your code here.
	}

	public void setimbAliasVisible(Boolean visible)
	{
		
		form.imbAlias().setVisible(visible);
	}

	public void setimbOtherNamesVisible(Boolean visible)
	{
		form.imbOtherNames().setVisible(visible);
	}

	public void setdteDodVisible(Boolean visible)
	{
		form.dteDod().setVisible(visible);
	}

	public void setdteDodEnabled(Boolean enabled)
	{
		form.dteDod().setEnabled(enabled);
	}

	public void setPatientDetailsFromPatientFilter(PatientFilter patientFilter) 
	{
		form.txtSurname().setValue(patientFilter.getSurname());
		form.txtForename().setValue(patientFilter.getForename());
		if (patientFilter.getSexIsNotNull())
			form.cmbSex().setValue(patientFilter.getSex());
		form.pdtDOB().setValue(patientFilter.getDob());
		form.imbOtherNames().setVisible(false);
		
	}

	public void setbtnDeceasedText(String text) 
	{
		form.btnDeceased().setText(text);
		
	}

	public void setbtnDeceasedVisible(Boolean visible) 
	{
		form.btnDeceased().setVisible(visible);
		
	}

	public void clear() 
	{
		form.cmbTitle().setValue(null);
		form.txtSurname().setValue(null);
		form.txtForename().setValue(null);
		form.txtMiddleName().setValue(null);
		form.cmbSex().setValue(null);
		form.pdtDOB().setValue(null);
		form.txtAge().setValue(null);
		form.dteDod().setValue(null);
		form.timTod().setValue(null);
		form.timTod().setTooltip(null);
		form.cmbMarital().setValue(null);
		form.qmbOccupation().clear();
		form.qmbOccupation().setValue(null);
		form.cmbReligion().setValue(null);
		form.cmbEthnic().setValue(null);
		
	}

	public Boolean populateScreenFromData(Patient pat) 
	{
		if (pat.getNameIsNotNull())
		{
			form.cmbTitle().setValue(pat.getName().getTitle());
			form.txtSurname().setValue(pat.getName().getSurname());
			form.txtForename().setValue(pat.getName().getForename());
			form.txtMiddleName().setValue(pat.getName().getMiddleName());
		}

		form.cmbSex().setValue(pat.getSex());
		form.pdtDOB().setValue(pat.getDob());
		form.txtAge().setValue(pat.calculateAgeText());
		form.dteDod().setValue(pat.getDod());
		form.timTod().setValue(pat.getTimeOfDeath());
		form.timTod().setTooltip(pat.getDodIsNotNull() && pat.getTimeOfDeath() ==  null ? "Time of Death<br/>Unknown/Not Recorded" : null);

		if (engine.hasRight(AppRight.ALLOW_MARK_PATIENT_AS_DECEASED) && form.getGlobalContext().Core.getPatientShort().getDodIsNotNull())
		{
			form.btnDeceased().setText("Death Details");
			form.btnDeceased().setVisible(true);
			
			//WDEV-16548
			form.dteDod().setVisible(true);
			form.timTod().setVisible(true);
			form.lblDod().setVisible(true);
			form.lblDod2().setVisible(true);
		}

		form.cmbMarital().setValue(pat.getMaritalStatus());
		if(pat.getOccupation() != null)
		{
			form.qmbOccupation().newRow(pat.getOccupation(), pat.getOccupation().getText());
		}
		form.qmbOccupation().setValue(pat.getOccupation());
		
		form.cmbReligion().setValue(pat.getReligion());
		form.cmbEthnic().setValue(pat.getEthnicOrigin());

		if (pat.getOtherNamesIsNotNull() && pat.getOtherNames().size() > 0)
		{
			if (pat.getMaidenName() != null)
			{
				form.imbOtherNames().setTooltip("<b>OTHER NAMES<br><br>Maiden Name:  </b>" + pat.getMaidenName().toString());
			}
			form.getGlobalContext().Core.setOtherNames(pat.getOtherNames());
		}
		else
		{
			form.imbOtherNames().setVisible(false);
			form.imbOtherNames().setTooltip("No Other Names");
		}

		if (ConfigFlag.DOM.USE_ALIAS_SURNAME_FUNCTIONALITY.getValue()) 
		{
			// WDEV-17457
			form.imbAlias().setTooltip("No Alias");
			form.imbAlias().setEnabledImage(form.getImages().Core.ZoomInfoEnabled24);
			form.imbAlias().setDisabledImage(form.getImages().Core.ZoomInfoDisabled24);

			form.getGlobalContext().Core.setAliasName(pat.getName(NameType.ALIAS) != null ? pat.getName(NameType.ALIAS).getSurname() : "");

			if (ConfigFlag.DOM.HEARTS_REPLICATE_PATIENTS.getValue())
			{
				//We have to do this DTO call to get ALIAS to Display - there is a time lag before the HL7inbound happens ... otherwise info on screen looks wrong 
				try 
				{
					if (form.getGlobalContext().Core.getPatientShort()!=null && form.getGlobalContext().Core.getPatientShort().getHospnum()!=null && form.getGlobalContext().Core.getPatientShort().getHospnum().getValue()!=null)//WDEV-17373
					{
						form.getGlobalContext().Core.setAliasName(domain.getCCOAlias(form.getGlobalContext().Core.getPatientShort().getHospnum().getValue()));
						
						//WDEV-17721
						if (form.getGlobalContext().Core.getAliasName() == null)
						{
							form.getGlobalContext().Core.setOtherNames(null);
							form.imbOtherNames().setTooltip("No Other Names");
						}
					}
				} 
				catch (DomainInterfaceException e) 
				{
					engine.showMessage(e.getMessage());
					//wdev-15845
					if(e.getMessage() != null && e.getMessage().equals("Demographics details cannot be edited –- Please contact the system administrator with the details for this patient"))
					{
						setDemographicDetailsCannotBeEdited(Boolean.TRUE);
					}
					else
						setDemographicDetailsCannotBeEdited(null);
					//-----------
					return Boolean.FALSE;
				}
			}
			
			if (form.getGlobalContext().Core.getAliasNameIsNotNull() && form.getGlobalContext().Core.getAliasName().trim().length() > 0) // WDEV-17457
			{
				form.imbAlias().setTooltip("<b>ALIAS :</b>   " + form.getGlobalContext().Core.getAliasName());
				form.imbAlias().setEnabledImage(form.getImages().Core.AddFile16);
				form.imbAlias().setDisabledImage(form.getImages().Core.AddFile16Disable);
			}
			
		}
		
		return Boolean.TRUE;


	}

	public void setlblDodVisible(Boolean visible) 
	{
		form.lblDod().setVisible(visible);
		
	}

	public void setlblDod2Visible(Boolean visible) 
	{
		form.lblDod2().setVisible(visible);
		
	}

	public void setdteDodValue(Date value) 
	{
		form.dteDod().setValue(value);		
	}

	public Boolean dteDodIsVisible() 
	{
		return form.dteDod().isVisible();

	}

	public PatientDetailsComponentVo getPatientDetails() 
	{
		PatientDetailsComponentVo tempVo = new PatientDetailsComponentVo();
		tempVo.setTitle(form.cmbTitle().getValue());
		tempVo.setForename(form.txtForename().getValue());
		tempVo.setMiddleName(form.txtMiddleName().getValue());
		tempVo.setSurname(form.txtSurname().getValue());
		
		tempVo.setSex(form.cmbSex().getValue());
		tempVo.setDob(form.pdtDOB().getValue());
		tempVo.setDod(form.dteDod().getValue());
		tempVo.setTimeOfDeath(form.timTod().getValue());
		tempVo.setMaritalStatus(form.cmbMarital().getValue());
		tempVo.setOccupation(form.qmbOccupation().getValue());
		tempVo.setReligion(form.cmbReligion().getValue());
		tempVo.setEthnicOrigin(form.cmbEthnic().getValue());
		
		return tempVo;
	}

	
	public void setimbAliasTooltip(String tooltip) 
	{
		form.imbAlias().setTooltip(tooltip);
		
	}

	
	public void setimbAliasEnabled(Boolean enabled) 
	{
		form.imbAlias().setEnabled(enabled);
		
	}

	public void setimbAliasEnabledImage(Image image) 
	{
		form.imbAlias().setEnabledImage(image);
		
	}

	public void setimbAliasDisabledImage(Image image) 
	{
		form.imbAlias().setDisabledImage(image);
		
	}

	//0- none, 1-imbOtherNames, 2 - imbAlias, 3 - btnDeceased
	public void setButtonAction(Integer action) 
	{
		form.getLocalContext().setButtonAction(action);
		
	}

	//0- none, 1-imbOtherNames, 2 - imbAlias, 3 - btnDeceased
	public Integer getButtonAction() 
	{
		
		return form.getLocalContext().getButtonAction();
	}

	public void setModeForm(FormMode mode) 
	{
		form.setMode(mode);
		
	}
	
	//wdev-15845
	public Boolean getDemographicDetailsCannotBeEdited()
	{
		return form.getLocalContext().getDemographicDetailsCannotBeEdited();
	}

	//wdev-15845
	public void setDemographicDetailsCannotBeEdited(Boolean canBeEdited)
	{
		form.getLocalContext().setDemographicDetailsCannotBeEdited(canBeEdited);
		
	}

	@Override
	protected void onQmbOccupationTextSubmited(String value) throws PresentationLogicException
	{
		populateOccupationQueryCombo(value);
	}

	private void populateOccupationQueryCombo(String value)
	{
		form.qmbOccupation().clear();
		
		if (value == null || value.length() == 0)
			return;

		OccupationCollection occupationColl = domain.getOccupations(value);

		if (occupationColl != null)
		{
			for (int i = 0; i < occupationColl.size(); i++)
			{
				form.qmbOccupation().newRow(occupationColl.get(i), occupationColl.get(i).getText());
			}
		}
		
		if (value != null && value.length() > 0)
			form.qmbOccupation().showOpened();
	}

	//wdev-19232
	public void setSVUHMandatoryFields()
	{
		form.cmbTitle().setRequired(true);
		form.txtForename().setRequired(true);
		//form.txtSurname().setRequired(true);
		form.cmbSex().setRequired(true);
		form.pdtDOB().setRequired(true);
		form.cmbMarital().setRequired(true);
		form.cmbReligion().setRequired(true);
		
		
	}

	//wdev-19528
	public void setConfigurableFields(DemographicControlsConfigVoCollection collfields)
	{
		if( collfields == null || collfields.size() == 0)
			return;
		
		for(int i = 0; i < collfields.size(); i++ )
		{
			DemographicControlsConfigVo tempVo = collfields.get(i); 
			if( tempVo != null )
			{
				if( TITLE_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.cmbTitle().setRequired(tempVo.getIsMandatory());
				}
				else if( FORENAME_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.txtForename().setRequired(tempVo.getIsMandatory());
				}
				else if( MIDDLENAME_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.txtMiddleName().setRequired(tempVo.getIsMandatory());
				}
				else if( SURNAME_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.txtSurname().setRequired(tempVo.getIsMandatory());
				}
				else if( SEX_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.cmbSex().setRequired(tempVo.getIsMandatory());
				}
				else if( DOB_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.pdtDOB().setRequired(tempVo.getIsMandatory());
				}
				else if( MARITAL_STATUS_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.cmbMarital().setRequired(tempVo.getIsMandatory());
				}
				else if( OCCUPATION_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.qmbOccupation().setRequired(tempVo.getIsMandatory());
				}
				else if( RELIGION_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.cmbReligion().setRequired(tempVo.getIsMandatory());
				}
				else if( ETHNIC_ORIGIN_DEMOGR.equals(tempVo.getControlIMSID()))
				{
					form.cmbEthnic().setRequired(tempVo.getIsMandatory());
				}
			}
		}
		
		
	}
	
	//wdev-19528
	public String[] getUIErrorsForConfigurableMode()
	{
		ArrayList<String> errors = new ArrayList<String>();

		if( form.cmbTitle().getVisible() && form.cmbTitle().isRequired() && form.cmbTitle().getValue() == null)
		{
			errors.add("Title is mandatory.");
		}
		if( form.txtForename().isVisible() && form.txtForename().isRequired() && (form.txtForename().getValue() == null || form.txtForename().getValue() == ""))
		{
			errors.add("Forename is mandatory.");
		}
		if( form.txtMiddleName().isVisible() && form.txtMiddleName().isRequired() && (form.txtMiddleName().getValue() == null || form.txtMiddleName().getValue() == ""))
		{
			errors.add("Middlename is mandatory.");
		}
		if( form.txtSurname().isVisible() && form.txtSurname().isRequired() && (form.txtSurname().getValue() == null || form.txtSurname().getValue() == ""))
		{
			errors.add("Surname is mandatory.");
		}
		if( form.cmbSex().getVisible() && form.cmbSex().isRequired() && form.cmbSex().getValue() == null)
		{
			errors.add("Sex is mandatory.");
		}
		if( form.pdtDOB().isVisible() && form.pdtDOB().isRequired() && form.pdtDOB().getValue() == null)
		{
			errors.add("DOB is mandatory.");
		}
		/*if( form.txtAge().isVisible() && form.txtAge().isRequired() && (form.txtAge().getValue() == null || form.txtAge().getValue() == ""))
		{
			errors.add("Age is mandatory.");
		}*/
		if( form.cmbMarital().getVisible() && form.cmbMarital().isRequired() && form.cmbMarital().getValue() == null)
		{
			errors.add("Marital Status is mandatory.");
		}
		if( form.qmbOccupation().getVisible() && form.qmbOccupation().isRequired() && form.qmbOccupation().getValue() == null)
		{
			errors.add("Occupation is mandatory.");
		}
		if( form.cmbReligion().getVisible() && form.cmbReligion().isRequired() && form.cmbReligion().getValue() == null)
		{
			errors.add("Religion is mandatory.");
		}
		if( form.cmbEthnic().getVisible() && form.cmbEthnic().isRequired() && form.cmbEthnic().getValue() == null)
		{
			errors.add("Ethnic Origin is mandatory.");
		}
		
		if( form.pdtDOB().isVisible() && form.pdtDOB().getValue() != null)   //wdev-13521
		{
			if( form.pdtDOB().getValue().isGreaterThan(new Date()))
			{
				errors.add("DOB cannot be in the future");
				
			}
		}
		if( form.dteDod().isVisible() && form.dteDod().getValue() != null)					//wdev-13521
		{
			if( form.dteDod().getValue().isGreaterThan(new Date()))
			{
				errors.add("DOD cannot be in the future");
				
			}
		}
		if( form.pdtDOB().isVisible() && form.dteDod().isVisible() && form.pdtDOB().getValue() != null && form.dteDod().getValue() != null)	//wdev-13521
		{
			if( form.dteDod().getValue().isLessThan(form.pdtDOB().getValue()))
			{
				errors.add("DOB cannot be after DOD");
				
			}
		}
		
		if( errors.size() > 0)
		{
			String[] UIErrors = new String[errors.size()];
			errors.toArray(UIErrors);
			return UIErrors;
		}

		return null;
	}

	public void settimTodValue(Time timeTod)
	{
		form.timTod().setValue(timeTod);		
	}

	public void settimTodVisible(Boolean visible)
	{
		form.timTod().setVisible(visible);
		
	}

	public void settimTodEnabled(Boolean enabled)
	{
		form.timTod().setEnabled(enabled);
		
	}

	public Boolean timTodIsVisible()
	{
		return form.timTod().isVisible();
	}
}
