//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.dtomove.vo.beans;

public class preTreatmentActionVoBean extends ims.vo.ValueObjectBean
{
	public preTreatmentActionVoBean()
	{
	}
	public preTreatmentActionVoBean(ims.dtomove.vo.preTreatmentActionVo vo)
	{
		this.id = vo.getBoId();
		this.version = vo.getBoVersion();
		this.actionname = vo.getActionName();
		this.actiondescription = vo.getActionDescription();
		this.isdefault = vo.getIsDefault();
		this.requiresmachine = vo.getRequiresMachine();
		this.activeidentifier = vo.getActiveIdentifier();
		this.requiresconsultant = vo.getRequiresConsultant();
		this.isdosecalcaction = vo.getIsDoseCalcAction();
		this.ismouldroomworklistitem = vo.getIsMouldRoomWorklistItem();
	}

	public void populate(ims.vo.ValueObjectBeanMap map, ims.dtomove.vo.preTreatmentActionVo vo)
	{
		this.id = vo.getBoId();
		this.version = vo.getBoVersion();
		this.actionname = vo.getActionName();
		this.actiondescription = vo.getActionDescription();
		this.isdefault = vo.getIsDefault();
		this.requiresmachine = vo.getRequiresMachine();
		this.activeidentifier = vo.getActiveIdentifier();
		this.requiresconsultant = vo.getRequiresConsultant();
		this.isdosecalcaction = vo.getIsDoseCalcAction();
		this.ismouldroomworklistitem = vo.getIsMouldRoomWorklistItem();
	}

	public ims.dtomove.vo.preTreatmentActionVo buildVo()
	{
		return this.buildVo(new ims.vo.ValueObjectBeanMap());
	}

	public ims.dtomove.vo.preTreatmentActionVo buildVo(ims.vo.ValueObjectBeanMap map)
	{
		ims.dtomove.vo.preTreatmentActionVo vo = null;
		if(map != null)
			vo = (ims.dtomove.vo.preTreatmentActionVo)map.getValueObject(this);
		if(vo == null)
		{
			vo = new ims.dtomove.vo.preTreatmentActionVo();
			map.addValueObject(this, vo);
			vo.populate(map, this);
		}
		return vo;
	}

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer value)
	{
		this.id = value;
	}
	public int getVersion()
	{
		return this.version;
	}
	public void setVersion(int value)
	{
		this.version = value;
	}
	public String getActionName()
	{
		return this.actionname;
	}
	public void setActionName(String value)
	{
		this.actionname = value;
	}
	public String getActionDescription()
	{
		return this.actiondescription;
	}
	public void setActionDescription(String value)
	{
		this.actiondescription = value;
	}
	public Boolean getIsDefault()
	{
		return this.isdefault;
	}
	public void setIsDefault(Boolean value)
	{
		this.isdefault = value;
	}
	public Boolean getRequiresMachine()
	{
		return this.requiresmachine;
	}
	public void setRequiresMachine(Boolean value)
	{
		this.requiresmachine = value;
	}
	public Boolean getActiveIdentifier()
	{
		return this.activeidentifier;
	}
	public void setActiveIdentifier(Boolean value)
	{
		this.activeidentifier = value;
	}
	public Boolean getRequiresConsultant()
	{
		return this.requiresconsultant;
	}
	public void setRequiresConsultant(Boolean value)
	{
		this.requiresconsultant = value;
	}
	public Boolean getIsDoseCalcAction()
	{
		return this.isdosecalcaction;
	}
	public void setIsDoseCalcAction(Boolean value)
	{
		this.isdosecalcaction = value;
	}
	public Boolean getIsMouldRoomWorklistItem()
	{
		return this.ismouldroomworklistitem;
	}
	public void setIsMouldRoomWorklistItem(Boolean value)
	{
		this.ismouldroomworklistitem = value;
	}

	private Integer id;
	private int version;
	private String actionname;
	private String actiondescription;
	private Boolean isdefault;
	private Boolean requiresmachine;
	private Boolean activeidentifier;
	private Boolean requiresconsultant;
	private Boolean isdosecalcaction;
	private Boolean ismouldroomworklistitem;
}
