//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.core.vo.beans;

public class BedSpaceInfoDialogVoBean extends ims.vo.ValueObjectBean
{
	public BedSpaceInfoDialogVoBean()
	{
	}
	public BedSpaceInfoDialogVoBean(ims.core.vo.BedSpaceInfoDialogVo vo)
	{
		this.hospitalno = vo.getHospitalNo();
		this.patientname = vo.getPatientName();
		this.address1 = vo.getAddress1();
		this.consultant = vo.getConsultant();
		this.instructions = vo.getInstructions();
		this.estimatedateofdischarge = vo.getEstimateDateOfDischarge();
		this.picture = vo.getPicture();
		this.address2 = vo.getAddress2();
		this.ward = vo.getWard();
	}

	public void populate(ims.vo.ValueObjectBeanMap map, ims.core.vo.BedSpaceInfoDialogVo vo)
	{
		this.hospitalno = vo.getHospitalNo();
		this.patientname = vo.getPatientName();
		this.address1 = vo.getAddress1();
		this.consultant = vo.getConsultant();
		this.instructions = vo.getInstructions();
		this.estimatedateofdischarge = vo.getEstimateDateOfDischarge();
		this.picture = vo.getPicture();
		this.address2 = vo.getAddress2();
		this.ward = vo.getWard();
	}

	public ims.core.vo.BedSpaceInfoDialogVo buildVo()
	{
		return this.buildVo(new ims.vo.ValueObjectBeanMap());
	}

	public ims.core.vo.BedSpaceInfoDialogVo buildVo(ims.vo.ValueObjectBeanMap map)
	{
		ims.core.vo.BedSpaceInfoDialogVo vo = null;
		if(map != null)
			vo = (ims.core.vo.BedSpaceInfoDialogVo)map.getValueObject(this);
		if(vo == null)
		{
			vo = new ims.core.vo.BedSpaceInfoDialogVo();
			map.addValueObject(this, vo);
			vo.populate(map, this);
		}
		return vo;
	}

	public String getHospitalNo()
	{
		return this.hospitalno;
	}
	public void setHospitalNo(String value)
	{
		this.hospitalno = value;
	}
	public String getPatientName()
	{
		return this.patientname;
	}
	public void setPatientName(String value)
	{
		this.patientname = value;
	}
	public String getAddress1()
	{
		return this.address1;
	}
	public void setAddress1(String value)
	{
		this.address1 = value;
	}
	public String getConsultant()
	{
		return this.consultant;
	}
	public void setConsultant(String value)
	{
		this.consultant = value;
	}
	public String getInstructions()
	{
		return this.instructions;
	}
	public void setInstructions(String value)
	{
		this.instructions = value;
	}
	public String getEstimateDateOfDischarge()
	{
		return this.estimatedateofdischarge;
	}
	public void setEstimateDateOfDischarge(String value)
	{
		this.estimatedateofdischarge = value;
	}
	public String getPicture()
	{
		return this.picture;
	}
	public void setPicture(String value)
	{
		this.picture = value;
	}
	public String getAddress2()
	{
		return this.address2;
	}
	public void setAddress2(String value)
	{
		this.address2 = value;
	}
	public String getWard()
	{
		return this.ward;
	}
	public void setWard(String value)
	{
		this.ward = value;
	}

	private String hospitalno;
	private String patientname;
	private String address1;
	private String consultant;
	private String instructions;
	private String estimatedateofdischarge;
	private String picture;
	private String address2;
	private String ward;
}
