//#############################################################################
//#                                                                           #
//#  Copyright (C) <2014>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5007.25751)
// Copyright (C) 1995-2014 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.core.forms.customlistmaintenance;

public abstract class BaseLogic extends Handlers
{
	public final Class getDomainInterface() throws ClassNotFoundException
	{
		return ims.core.domain.CustomListMaintenance.class;
	}
	public final void setContext(ims.framework.UIEngine engine, GenForm form, ims.core.domain.CustomListMaintenance domain)
	{
		setContext(engine, form);
		this.domain = domain;
	}
	protected final void oncmbSpecialtyValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.lyrCustomListSearch().tabCustomListSearch().cmbSpecialty().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.Specialty existingInstance = (ims.core.vo.lookups.Specialty)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbSpecialtyLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.core.vo.lookups.Specialty)
		{
			ims.core.vo.lookups.Specialty instance = (ims.core.vo.lookups.Specialty)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbSpecialtyLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.Specialty existingInstance = (ims.core.vo.lookups.Specialty)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.lyrCustomListSearch().tabCustomListSearch().cmbSpecialty().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbSpecialtyLookup()
	{
		this.form.lyrCustomListSearch().tabCustomListSearch().cmbSpecialty().clear();
		ims.core.vo.lookups.SpecialtyCollection lookupCollection = ims.core.vo.lookups.LookupHelper.getSpecialty(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.lyrCustomListSearch().tabCustomListSearch().cmbSpecialty().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbSpecialtyLookupValue(int id)
	{
		ims.core.vo.lookups.Specialty instance = ims.core.vo.lookups.LookupHelper.getSpecialtyInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.lyrCustomListSearch().tabCustomListSearch().cmbSpecialty().setValue(instance);
	}
	protected final void defaultcmbSpecialtyLookupValue()
	{
		this.form.lyrCustomListSearch().tabCustomListSearch().cmbSpecialty().setValue((ims.core.vo.lookups.Specialty)domain.getLookupService().getDefaultInstance(ims.core.vo.lookups.Specialty.class, engine.getFormName().getID(), ims.core.vo.lookups.Specialty.TYPE_ID));
	}
	protected final void oncmbListTypeValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.lyrCustomListSearch().tabCustomListSearch().cmbListType().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.CustomListType existingInstance = (ims.core.vo.lookups.CustomListType)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbListTypeLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.core.vo.lookups.CustomListType)
		{
			ims.core.vo.lookups.CustomListType instance = (ims.core.vo.lookups.CustomListType)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbListTypeLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.CustomListType existingInstance = (ims.core.vo.lookups.CustomListType)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.lyrCustomListSearch().tabCustomListSearch().cmbListType().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbListTypeLookup()
	{
		this.form.lyrCustomListSearch().tabCustomListSearch().cmbListType().clear();
		ims.core.vo.lookups.CustomListTypeCollection lookupCollection = ims.core.vo.lookups.LookupHelper.getCustomListType(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.lyrCustomListSearch().tabCustomListSearch().cmbListType().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbListTypeLookupValue(int id)
	{
		ims.core.vo.lookups.CustomListType instance = ims.core.vo.lookups.LookupHelper.getCustomListTypeInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.lyrCustomListSearch().tabCustomListSearch().cmbListType().setValue(instance);
	}
	protected final void defaultcmbListTypeLookupValue()
	{
		this.form.lyrCustomListSearch().tabCustomListSearch().cmbListType().setValue((ims.core.vo.lookups.CustomListType)domain.getLookupService().getDefaultInstance(ims.core.vo.lookups.CustomListType.class, engine.getFormName().getID(), ims.core.vo.lookups.CustomListType.TYPE_ID));
	}
	protected final void oncmbSpecialtyDetailsValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.lyrCustomListSearch().tabCustomListDetails().cmbSpecialtyDetails().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.Specialty existingInstance = (ims.core.vo.lookups.Specialty)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbSpecialtyDetailsLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.core.vo.lookups.Specialty)
		{
			ims.core.vo.lookups.Specialty instance = (ims.core.vo.lookups.Specialty)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbSpecialtyDetailsLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.Specialty existingInstance = (ims.core.vo.lookups.Specialty)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.lyrCustomListSearch().tabCustomListDetails().cmbSpecialtyDetails().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbSpecialtyDetailsLookup()
	{
		this.form.lyrCustomListSearch().tabCustomListDetails().cmbSpecialtyDetails().clear();
		ims.core.vo.lookups.SpecialtyCollection lookupCollection = ims.core.vo.lookups.LookupHelper.getSpecialty(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.lyrCustomListSearch().tabCustomListDetails().cmbSpecialtyDetails().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbSpecialtyDetailsLookupValue(int id)
	{
		ims.core.vo.lookups.Specialty instance = ims.core.vo.lookups.LookupHelper.getSpecialtyInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.lyrCustomListSearch().tabCustomListDetails().cmbSpecialtyDetails().setValue(instance);
	}
	protected final void defaultcmbSpecialtyDetailsLookupValue()
	{
		this.form.lyrCustomListSearch().tabCustomListDetails().cmbSpecialtyDetails().setValue((ims.core.vo.lookups.Specialty)domain.getLookupService().getDefaultInstance(ims.core.vo.lookups.Specialty.class, engine.getFormName().getID(), ims.core.vo.lookups.Specialty.TYPE_ID));
	}
	protected final void oncmbListTypeDetailsValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.lyrCustomListSearch().tabCustomListDetails().cmbListTypeDetails().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.CustomListType existingInstance = (ims.core.vo.lookups.CustomListType)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbListTypeDetailsLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.core.vo.lookups.CustomListType)
		{
			ims.core.vo.lookups.CustomListType instance = (ims.core.vo.lookups.CustomListType)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbListTypeDetailsLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.CustomListType existingInstance = (ims.core.vo.lookups.CustomListType)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.lyrCustomListSearch().tabCustomListDetails().cmbListTypeDetails().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbListTypeDetailsLookup()
	{
		this.form.lyrCustomListSearch().tabCustomListDetails().cmbListTypeDetails().clear();
		ims.core.vo.lookups.CustomListTypeCollection lookupCollection = ims.core.vo.lookups.LookupHelper.getCustomListType(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.lyrCustomListSearch().tabCustomListDetails().cmbListTypeDetails().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbListTypeDetailsLookupValue(int id)
	{
		ims.core.vo.lookups.CustomListType instance = ims.core.vo.lookups.LookupHelper.getCustomListTypeInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.lyrCustomListSearch().tabCustomListDetails().cmbListTypeDetails().setValue(instance);
	}
	protected final void defaultcmbListTypeDetailsLookupValue()
	{
		this.form.lyrCustomListSearch().tabCustomListDetails().cmbListTypeDetails().setValue((ims.core.vo.lookups.CustomListType)domain.getLookupService().getDefaultInstance(ims.core.vo.lookups.CustomListType.class, engine.getFormName().getID(), ims.core.vo.lookups.CustomListType.TYPE_ID));
	}
	public final void free()
	{
		super.free();
		domain = null;
	}
	
	protected ims.core.domain.CustomListMaintenance domain;
}
