//#############################################################################
//#                                                                           #
//#  Copyright (C) <2014>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5007.25751)
// Copyright (C) 1995-2014 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.ocrr.domain;

// Generated from form domain impl
public interface CumulateResults extends ims.domain.DomainInterface
{
	// Generated from form domain interface definition
	/**
	* lists all results
	*/
	public ims.core.vo.ChartResultVoCollection listResults(ims.core.patient.vo.PatientRefVo patient, ims.ocrr.configuration.vo.AnalyteRefVoCollection analytes, ims.framework.utils.Date startDate, ims.framework.utils.Date endDate, Boolean isTabularView) throws ims.domain.exceptions.DomainInterfaceException;

	// Generated from form domain interface definition
	public ims.core.vo.DataSetTypeVo getDataset(ims.ocrr.configuration.vo.AnalyteRefVo analyte);

	// Generated from form domain interface definition
	public ims.ocrr.vo.OrderInvestigationVo getOrder(ims.ocrr.orderingresults.vo.OrderInvestigationRefVo orderRef);

	// Generated from form domain interface definition
	public ims.ocrr.vo.OrderSpecimenLiteVo getOrderSpecimen(ims.ocrr.orderingresults.vo.OrderSpecimenRefVo specimenRef);

	// Generated from form domain interface definition
	public ims.ocrr.vo.OrderInvestigationDFTForCumulateResultsVo getDTFOrderInvestigation(ims.ocrr.orderingresults.vo.OrderInvestigationRefVo orderInvestigationRef);

	// Generated from form domain interface definition
	public ims.ocrr.vo.OrderInvestigationChartVo getOrderInvestigation(ims.ocrr.orderingresults.vo.OrderInvestigationRefVo orderInvestigationRef);
}
