//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.RefMan.vo.beans;

public class ClinicalOutcomeLiteVoBean extends ims.vo.ValueObjectBean
{
	public ClinicalOutcomeLiteVoBean()
	{
	}
	public ClinicalOutcomeLiteVoBean(ims.RefMan.vo.ClinicalOutcomeLiteVo vo)
	{
		this.id = vo.getBoId();
		this.version = vo.getBoVersion();
		this.clinicaloutcome = vo.getClinicalOutcome() == null ? null : (ims.clinicaladmin.vo.beans.ClinicalOutcomeConfigLiteVoBean)vo.getClinicalOutcome().getBean();
		this.date = vo.getDate() == null ? null : (ims.framework.utils.beans.DateBean)vo.getDate().getBean();
		this.procedure = vo.getProcedure() == null ? null : (ims.RefMan.vo.beans.ClinicalOutcomeProcedureVoBean)vo.getProcedure().getBean();
		this.clinicaloutcomecontext = vo.getClinicalOutcomeContext() == null ? null : (ims.vo.LookupInstanceBean)vo.getClinicalOutcomeContext().getBean();
	}

	public void populate(ims.vo.ValueObjectBeanMap map, ims.RefMan.vo.ClinicalOutcomeLiteVo vo)
	{
		this.id = vo.getBoId();
		this.version = vo.getBoVersion();
		this.clinicaloutcome = vo.getClinicalOutcome() == null ? null : (ims.clinicaladmin.vo.beans.ClinicalOutcomeConfigLiteVoBean)vo.getClinicalOutcome().getBean(map);
		this.date = vo.getDate() == null ? null : (ims.framework.utils.beans.DateBean)vo.getDate().getBean();
		this.procedure = vo.getProcedure() == null ? null : (ims.RefMan.vo.beans.ClinicalOutcomeProcedureVoBean)vo.getProcedure().getBean(map);
		this.clinicaloutcomecontext = vo.getClinicalOutcomeContext() == null ? null : (ims.vo.LookupInstanceBean)vo.getClinicalOutcomeContext().getBean();
	}

	public ims.RefMan.vo.ClinicalOutcomeLiteVo buildVo()
	{
		return this.buildVo(new ims.vo.ValueObjectBeanMap());
	}

	public ims.RefMan.vo.ClinicalOutcomeLiteVo buildVo(ims.vo.ValueObjectBeanMap map)
	{
		ims.RefMan.vo.ClinicalOutcomeLiteVo vo = null;
		if(map != null)
			vo = (ims.RefMan.vo.ClinicalOutcomeLiteVo)map.getValueObject(this);
		if(vo == null)
		{
			vo = new ims.RefMan.vo.ClinicalOutcomeLiteVo();
			map.addValueObject(this, vo);
			vo.populate(map, this);
		}
		return vo;
	}

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer value)
	{
		this.id = value;
	}
	public int getVersion()
	{
		return this.version;
	}
	public void setVersion(int value)
	{
		this.version = value;
	}
	public ims.clinicaladmin.vo.beans.ClinicalOutcomeConfigLiteVoBean getClinicalOutcome()
	{
		return this.clinicaloutcome;
	}
	public void setClinicalOutcome(ims.clinicaladmin.vo.beans.ClinicalOutcomeConfigLiteVoBean value)
	{
		this.clinicaloutcome = value;
	}
	public ims.framework.utils.beans.DateBean getDate()
	{
		return this.date;
	}
	public void setDate(ims.framework.utils.beans.DateBean value)
	{
		this.date = value;
	}
	public ims.RefMan.vo.beans.ClinicalOutcomeProcedureVoBean getProcedure()
	{
		return this.procedure;
	}
	public void setProcedure(ims.RefMan.vo.beans.ClinicalOutcomeProcedureVoBean value)
	{
		this.procedure = value;
	}
	public ims.vo.LookupInstanceBean getClinicalOutcomeContext()
	{
		return this.clinicaloutcomecontext;
	}
	public void setClinicalOutcomeContext(ims.vo.LookupInstanceBean value)
	{
		this.clinicaloutcomecontext = value;
	}

	private Integer id;
	private int version;
	private ims.clinicaladmin.vo.beans.ClinicalOutcomeConfigLiteVoBean clinicaloutcome;
	private ims.framework.utils.beans.DateBean date;
	private ims.RefMan.vo.beans.ClinicalOutcomeProcedureVoBean procedure;
	private ims.vo.LookupInstanceBean clinicaloutcomecontext;
}
