//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.scheduling.vo.lookups;

import ims.framework.cn.data.TreeNode;
import java.util.ArrayList;
import ims.framework.utils.Image;
import ims.framework.utils.Color;

public class PendingEmergencyTheatreStatus extends ims.vo.LookupInstVo implements TreeNode
{
	private static final long serialVersionUID = 1L;

	public PendingEmergencyTheatreStatus()
	{
		super();
	}
	public PendingEmergencyTheatreStatus(int id)
	{
		super(id, "", true);
	}
	public PendingEmergencyTheatreStatus(int id, String text, boolean active)
	{
		super(id, text, active, null, null, null);
	}
	public PendingEmergencyTheatreStatus(int id, String text, boolean active, PendingEmergencyTheatreStatus parent, Image image)
	{
		super(id, text, active, parent, image);
	}
	public PendingEmergencyTheatreStatus(int id, String text, boolean active, PendingEmergencyTheatreStatus parent, Image image, Color color)
	{
		super(id, text, active, parent, image, color);
	}
	public PendingEmergencyTheatreStatus(int id, String text, boolean active, PendingEmergencyTheatreStatus parent, Image image, Color color, int order)
	{
		super(id, text, active, parent, image, color, order);
	}
	public static PendingEmergencyTheatreStatus buildLookup(ims.vo.LookupInstanceBean bean)
	{
		return new PendingEmergencyTheatreStatus(bean.getId(), bean.getText(), bean.isActive());
	}
	public String toString()
	{
		if(getText() != null)
			return getText();
		return "";
	}
	public TreeNode getParentNode()
	{
		return (PendingEmergencyTheatreStatus)super.getParentInstance();
	}
	public PendingEmergencyTheatreStatus getParent()
	{
		return (PendingEmergencyTheatreStatus)super.getParentInstance();
	}
	public void setParent(PendingEmergencyTheatreStatus parent)
	{
		super.setParentInstance(parent);
	}
	public TreeNode[] getChildren()
	{
		ArrayList children = super.getChildInstances();
		PendingEmergencyTheatreStatus[] typedChildren = new PendingEmergencyTheatreStatus[children.size()];
		for (int i = 0; i < children.size(); i++)
		{
			typedChildren[i] = (PendingEmergencyTheatreStatus)children.get(i);
		}
		return typedChildren;
	}
	public int addChild(TreeNode child)
	{
		if (child instanceof PendingEmergencyTheatreStatus)
		{
			super.addChild((PendingEmergencyTheatreStatus)child);
		}
		return super.getChildInstances().size();
	}
	public int removeChild(TreeNode child)
	{
		if (child instanceof PendingEmergencyTheatreStatus)
		{
			super.removeChild((PendingEmergencyTheatreStatus)child);
		}
		return super.getChildInstances().size();
	}
	public Image getExpandedImage()
	{
		return super.getImage();
	}
	public Image getCollapsedImage()
	{
		return super.getImage();
	}
	public static ims.framework.IItemCollection getNegativeInstancesAsIItemCollection()
	{
		PendingEmergencyTheatreStatusCollection result = new PendingEmergencyTheatreStatusCollection();
		result.add(THEATRE_SLOT_TO_BE_BOOKED);
		result.add(THEATRE_SLOT_BOOKED);
		result.add(REMOVED);
		result.add(ADMITTED);
		return result;
	}
	public static PendingEmergencyTheatreStatus[] getNegativeInstances()
	{
		PendingEmergencyTheatreStatus[] instances = new PendingEmergencyTheatreStatus[4];
		instances[0] = THEATRE_SLOT_TO_BE_BOOKED;
		instances[1] = THEATRE_SLOT_BOOKED;
		instances[2] = REMOVED;
		instances[3] = ADMITTED;
		return instances;
	}
	public static String[] getNegativeInstanceNames()
	{
		String[] negativeInstances = new String[4];
		negativeInstances[0] = "THEATRE_SLOT_TO_BE_BOOKED";
		negativeInstances[1] = "THEATRE_SLOT_BOOKED";
		negativeInstances[2] = "REMOVED";
		negativeInstances[3] = "ADMITTED";
		return negativeInstances;
	}
	public static PendingEmergencyTheatreStatus getNegativeInstance(String name)
	{
		if(name == null)
			return null;
		String[] negativeInstances = getNegativeInstanceNames();
		for (int i = 0; i < negativeInstances.length; i++)
		{
			if(negativeInstances[i].equals(name))
				return getNegativeInstances()[i];
		}
		return null;
	}
	public static PendingEmergencyTheatreStatus getNegativeInstance(Integer id)
	{
		if(id == null)
			return null;
		PendingEmergencyTheatreStatus[] negativeInstances = getNegativeInstances();
		for (int i = 0; i < negativeInstances.length; i++)
		{
			if(negativeInstances[i].getID() == id)
				return negativeInstances[i];
		}
		return null;
	}
	public int getTypeId()
	{
		return TYPE_ID;
	}
	public static final int TYPE_ID = 1141039;
	public static final PendingEmergencyTheatreStatus THEATRE_SLOT_TO_BE_BOOKED = new PendingEmergencyTheatreStatus(-3302, "Theatre Slot To be booked", true, null, null, Color.Default);
	public static final PendingEmergencyTheatreStatus THEATRE_SLOT_BOOKED = new PendingEmergencyTheatreStatus(-3303, "Theatre Slot Booked", true, null, null, Color.Default);
	public static final PendingEmergencyTheatreStatus REMOVED = new PendingEmergencyTheatreStatus(-3304, "Removed", true, null, null, Color.Default);
	public static final PendingEmergencyTheatreStatus ADMITTED = new PendingEmergencyTheatreStatus(-3305, "Admitted", true, null, null, Color.Default);
}
