//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.dtomove.vo;

/**
 * Linked to dto_move.Group business object (ID: 1105100000).
 */
public class GroupVo extends ims.dto_move.vo.GroupRefVo implements ims.vo.ImsCloneable, Comparable
{
	private static final long serialVersionUID = 1L;

	public GroupVo()
	{
	}
	public GroupVo(Integer id, int version)
	{
		super(id, version);
	}
	public GroupVo(ims.dtomove.vo.beans.GroupVoBean bean)
	{
		this.id = bean.getId();
		this.version = bean.getVersion();
		this.name = bean.getName();
		this.active = bean.getActive();
		this.technique = ims.dtomove.vo.GroupTechniqueVoCollection.buildFromBeanCollection(bean.getTechnique());
		this.site = ims.dtomove.vo.GroupSiteVoCollection.buildFromBeanCollection(bean.getSite());
	}
	public void populate(ims.vo.ValueObjectBeanMap map, ims.dtomove.vo.beans.GroupVoBean bean)
	{
		this.id = bean.getId();
		this.version = bean.getVersion();
		this.name = bean.getName();
		this.active = bean.getActive();
		this.technique = ims.dtomove.vo.GroupTechniqueVoCollection.buildFromBeanCollection(bean.getTechnique());
		this.site = ims.dtomove.vo.GroupSiteVoCollection.buildFromBeanCollection(bean.getSite());
	}
	public ims.vo.ValueObjectBean getBean()
	{
		return this.getBean(new ims.vo.ValueObjectBeanMap());
	}
	public ims.vo.ValueObjectBean getBean(ims.vo.ValueObjectBeanMap map)
	{
		ims.dtomove.vo.beans.GroupVoBean bean = null;
		if(map != null)
			bean = (ims.dtomove.vo.beans.GroupVoBean)map.getValueObjectBean(this);
		if (bean == null)
		{
			bean = new ims.dtomove.vo.beans.GroupVoBean();
			map.addValueObjectBean(this, bean);
			bean.populate(map, this);
		}
		return bean;
	}
	public Object getFieldValueByFieldName(String fieldName)
	{
		if(fieldName == null)
			throw new ims.framework.exceptions.CodingRuntimeException("Invalid field name");
		fieldName = fieldName.toUpperCase();
		if(fieldName.equals("NAME"))
			return getName();
		if(fieldName.equals("ACTIVE"))
			return getActive();
		if(fieldName.equals("TECHNIQUE"))
			return getTechnique();
		if(fieldName.equals("SITE"))
			return getSite();
		return super.getFieldValueByFieldName(fieldName);
	}
	public boolean getNameIsNotNull()
	{
		return this.name != null;
	}
	public String getName()
	{
		return this.name;
	}
	public static int getNameMaxLength()
	{
		return 70;
	}
	public void setName(String value)
	{
		this.isValidated = false;
		this.name = value;
	}
	public boolean getActiveIsNotNull()
	{
		return this.active != null;
	}
	public String getActive()
	{
		return this.active;
	}
	public static int getActiveMaxLength()
	{
		return 1;
	}
	public void setActive(String value)
	{
		this.isValidated = false;
		this.active = value;
	}
	public boolean getTechniqueIsNotNull()
	{
		return this.technique != null;
	}
	public ims.dtomove.vo.GroupTechniqueVoCollection getTechnique()
	{
		return this.technique;
	}
	public void setTechnique(ims.dtomove.vo.GroupTechniqueVoCollection value)
	{
		this.isValidated = false;
		this.technique = value;
	}
	public boolean getSiteIsNotNull()
	{
		return this.site != null;
	}
	public ims.dtomove.vo.GroupSiteVoCollection getSite()
	{
		return this.site;
	}
	public void setSite(ims.dtomove.vo.GroupSiteVoCollection value)
	{
		this.isValidated = false;
		this.site = value;
	}
	public boolean isValidated()
	{
		if(this.isBusy)
			return true;
		this.isBusy = true;
	
		if(!this.isValidated)
		{
			this.isBusy = false;
			return false;
		}
		this.isBusy = false;
		return true;
	}
	public String[] validate()
	{
		return validate(null);
	}
	public String[] validate(String[] existingErrors)
	{
		if(this.isBusy)
			return null;
		this.isBusy = true;
	
		java.util.ArrayList<String> listOfErrors = new java.util.ArrayList<String>();
		if(existingErrors != null)
		{
			for(int x = 0; x < existingErrors.length; x++)
			{
				listOfErrors.add(existingErrors[x]);
			}
		}
		if(this.name != null)
			if(this.name.length() > 70)
				listOfErrors.add("The length of the field [name] in the value object [ims.dtomove.vo.GroupVo] is too big. It should be less or equal to 70");
		if(this.active != null)
			if(this.active.length() > 1)
				listOfErrors.add("The length of the field [active] in the value object [ims.dtomove.vo.GroupVo] is too big. It should be less or equal to 1");
		int errorCount = listOfErrors.size();
		if(errorCount == 0)
		{
			this.isBusy = false;
			this.isValidated = true;
			return null;
		}
		String[] result = new String[errorCount];
		for(int x = 0; x < errorCount; x++)
			result[x] = (String)listOfErrors.get(x);
		this.isBusy = false;
		this.isValidated = false;
		return result;
	}
	public void clearIDAndVersion()
	{
		this.id = null;
		this.version = 0;
	}
	public Object clone()
	{
		if(this.isBusy)
			return this;
		this.isBusy = true;
	
		GroupVo clone = new GroupVo(this.id, this.version);
		
		clone.name = this.name;
		clone.active = this.active;
		if(this.technique == null)
			clone.technique = null;
		else
			clone.technique = (ims.dtomove.vo.GroupTechniqueVoCollection)this.technique.clone();
		if(this.site == null)
			clone.site = null;
		else
			clone.site = (ims.dtomove.vo.GroupSiteVoCollection)this.site.clone();
		clone.isValidated = this.isValidated;
		
		this.isBusy = false;
		return clone;
	}
	public int compareTo(Object obj)
	{
		return compareTo(obj, true);
	}
	public int compareTo(Object obj, boolean caseInsensitive)
	{
		if (obj == null)
		{
			return -1;
		}
		if(caseInsensitive); // this is to avoid eclipse warning only.
		if (!(GroupVo.class.isAssignableFrom(obj.getClass())))
		{
			throw new ClassCastException("A GroupVo object cannot be compared an Object of type " + obj.getClass().getName());
		}
		if (this.id == null)
			return 1;
		if (((GroupVo)obj).getBoId() == null)
			return -1;
		return this.id.compareTo(((GroupVo)obj).getBoId());
	}
	public synchronized static int generateValueObjectUniqueID()
	{
		return ims.vo.ValueObject.generateUniqueID();
	}
	public int countFieldsWithValue()
	{
		int count = 0;
		if(this.name != null)
			count++;
		if(this.active != null)
			count++;
		if(this.technique != null)
			count++;
		if(this.site != null)
			count++;
		return count;
	}
	public int countValueObjectFields()
	{
		return 4;
	}
	protected String name;
	protected String active;
	protected ims.dtomove.vo.GroupTechniqueVoCollection technique;
	protected ims.dtomove.vo.GroupSiteVoCollection site;
	private boolean isValidated = false;
	private boolean isBusy = false;
}
