//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.clinicaladmin.forms.internalreferralmoduleconfiguration;

public abstract class BaseLogic extends Handlers
{
	public final Class getDomainInterface() throws ClassNotFoundException
	{
		return ims.clinicaladmin.domain.InternalReferralModuleConfiguration.class;
	}
	public final void setContext(ims.framework.UIEngine engine, GenForm form, ims.clinicaladmin.domain.InternalReferralModuleConfiguration domain)
	{
		setContext(engine, form);
		this.domain = domain;
	}
	public void clearContextInformation()
	{
		engine.clearPatientContextInformation();
	}
	protected final void oncmbInternalReferralStatusValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.lyrMain().tabPageInternalReferralWorkflow().cmbInternalReferralStatus().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.InternalReferralStatus existingInstance = (ims.core.vo.lookups.InternalReferralStatus)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbInternalReferralStatusLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.core.vo.lookups.InternalReferralStatus)
		{
			ims.core.vo.lookups.InternalReferralStatus instance = (ims.core.vo.lookups.InternalReferralStatus)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbInternalReferralStatusLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.core.vo.lookups.InternalReferralStatus existingInstance = (ims.core.vo.lookups.InternalReferralStatus)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.lyrMain().tabPageInternalReferralWorkflow().cmbInternalReferralStatus().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbInternalReferralStatusLookup()
	{
		this.form.lyrMain().tabPageInternalReferralWorkflow().cmbInternalReferralStatus().clear();
		ims.core.vo.lookups.InternalReferralStatusCollection lookupCollection = ims.core.vo.lookups.LookupHelper.getInternalReferralStatus(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.lyrMain().tabPageInternalReferralWorkflow().cmbInternalReferralStatus().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbInternalReferralStatusLookupValue(int id)
	{
		ims.core.vo.lookups.InternalReferralStatus instance = ims.core.vo.lookups.LookupHelper.getInternalReferralStatusInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.lyrMain().tabPageInternalReferralWorkflow().cmbInternalReferralStatus().setValue(instance);
	}
	protected final void defaultcmbInternalReferralStatusLookupValue()
	{
		this.form.lyrMain().tabPageInternalReferralWorkflow().cmbInternalReferralStatus().setValue((ims.core.vo.lookups.InternalReferralStatus)domain.getLookupService().getDefaultInstance(ims.core.vo.lookups.InternalReferralStatus.class, engine.getFormName().getID(), ims.core.vo.lookups.InternalReferralStatus.TYPE_ID));
	}
	protected final void oncmbNewConditionBackToGPValueSet(Object value)
	{
		java.util.ArrayList listOfValues = this.form.lyrMain().tabPageInternalReferralSettings().cmbNewConditionBackToGP().getValues();

		if(value == null)
		{
			if(listOfValues != null && listOfValues.size() > 0)
			{
				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP existingInstance = (ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP)listOfValues.get(x);
					if(!existingInstance.isActive())
					{
						bindcmbNewConditionBackToGPLookup();
						return;
					}
				}
			}
		}
		else if(value instanceof ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP)
		{
			ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP instance = (ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP)value;

			if(listOfValues != null)
			{
				if(listOfValues.size() == 0)
					bindcmbNewConditionBackToGPLookup();

				for(int x = 0; x < listOfValues.size(); x++)
				{
					ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP existingInstance = (ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP)listOfValues.get(x);
					if(existingInstance.equals(instance))
						return;
				}
			}

			this.form.lyrMain().tabPageInternalReferralSettings().cmbNewConditionBackToGP().newRow(instance, instance.getText(), instance.getImage(), instance.getTextColor());
		}
	}
	protected final void bindcmbNewConditionBackToGPLookup()
	{
		this.form.lyrMain().tabPageInternalReferralSettings().cmbNewConditionBackToGP().clear();
		ims.clinical.vo.lookups.InternalReferralConditionalReferralToGPCollection lookupCollection = ims.clinical.vo.lookups.LookupHelper.getInternalReferralConditionalReferralToGP(this.domain.getLookupService());
		for(int x = 0; x < lookupCollection.size(); x++)
		{
			this.form.lyrMain().tabPageInternalReferralSettings().cmbNewConditionBackToGP().newRow(lookupCollection.get(x), lookupCollection.get(x).getText(), lookupCollection.get(x).getImage(), lookupCollection.get(x).getTextColor());
		}
	}
	protected final void setcmbNewConditionBackToGPLookupValue(int id)
	{
		ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP instance = ims.clinical.vo.lookups.LookupHelper.getInternalReferralConditionalReferralToGPInstance(this.domain.getLookupService(), id);
		if(instance != null)
			this.form.lyrMain().tabPageInternalReferralSettings().cmbNewConditionBackToGP().setValue(instance);
	}
	protected final void defaultcmbNewConditionBackToGPLookupValue()
	{
		this.form.lyrMain().tabPageInternalReferralSettings().cmbNewConditionBackToGP().setValue((ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP)domain.getLookupService().getDefaultInstance(ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP.class, engine.getFormName().getID(), ims.clinical.vo.lookups.InternalReferralConditionalReferralToGP.TYPE_ID));
	}
	public final void free()
	{
		super.free();
		domain = null;
	}
	
	protected ims.clinicaladmin.domain.InternalReferralModuleConfiguration domain;
}
