//#############################################################################
//#                                                                           #
//#  Copyright (C) <2015>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#  IMS MAXIMS provides absolutely NO GUARANTEE OF THE CLINICAL SAFTEY of    #
//#  this program.  Users of this software do so entirely at their own risk.  #
//#  IMS MAXIMS only ensures the Clinical Safety of unaltered run-time        #
//#  software that it builds, deploys and maintains.                          #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5589.25814)
// Copyright (C) 1995-2015 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.core.vo.lookups;

import ims.framework.cn.data.TreeNode;
import java.util.ArrayList;
import ims.framework.utils.Image;
import ims.framework.utils.Color;

public class CaseNoteStatus extends ims.vo.LookupInstVo implements TreeNode
{
	private static final long serialVersionUID = 1L;

	public CaseNoteStatus()
	{
		super();
	}
	public CaseNoteStatus(int id)
	{
		super(id, "", true);
	}
	public CaseNoteStatus(int id, String text, boolean active)
	{
		super(id, text, active, null, null, null);
	}
	public CaseNoteStatus(int id, String text, boolean active, CaseNoteStatus parent, Image image)
	{
		super(id, text, active, parent, image);
	}
	public CaseNoteStatus(int id, String text, boolean active, CaseNoteStatus parent, Image image, Color color)
	{
		super(id, text, active, parent, image, color);
	}
	public CaseNoteStatus(int id, String text, boolean active, CaseNoteStatus parent, Image image, Color color, int order)
	{
		super(id, text, active, parent, image, color, order);
	}
	public static CaseNoteStatus buildLookup(ims.vo.LookupInstanceBean bean)
	{
		return new CaseNoteStatus(bean.getId(), bean.getText(), bean.isActive());
	}
	public String toString()
	{
		if(getText() != null)
			return getText();
		return "";
	}
	public TreeNode getParentNode()
	{
		return (CaseNoteStatus)super.getParentInstance();
	}
	public CaseNoteStatus getParent()
	{
		return (CaseNoteStatus)super.getParentInstance();
	}
	public void setParent(CaseNoteStatus parent)
	{
		super.setParentInstance(parent);
	}
	public TreeNode[] getChildren()
	{
		ArrayList children = super.getChildInstances();
		CaseNoteStatus[] typedChildren = new CaseNoteStatus[children.size()];
		for (int i = 0; i < children.size(); i++)
		{
			typedChildren[i] = (CaseNoteStatus)children.get(i);
		}
		return typedChildren;
	}
	public int addChild(TreeNode child)
	{
		if (child instanceof CaseNoteStatus)
		{
			super.addChild((CaseNoteStatus)child);
		}
		return super.getChildInstances().size();
	}
	public int removeChild(TreeNode child)
	{
		if (child instanceof CaseNoteStatus)
		{
			super.removeChild((CaseNoteStatus)child);
		}
		return super.getChildInstances().size();
	}
	public Image getExpandedImage()
	{
		return super.getImage();
	}
	public Image getCollapsedImage()
	{
		return super.getImage();
	}
	public static ims.framework.IItemCollection getNegativeInstancesAsIItemCollection()
	{
		CaseNoteStatusCollection result = new CaseNoteStatusCollection();
		result.add(ACTIVE);
		result.add(ARCHIVED);
		result.add(DESTROYED);
		result.add(MERGED);
		result.add(SCANNED);
		result.add(MARKED_AS_FOUND);
		result.add(MISSING);
		result.add(REQUIRES_MERGING);
		result.add(REQUIRES_CASE_NOTES);
		return result;
	}
	public static CaseNoteStatus[] getNegativeInstances()
	{
		CaseNoteStatus[] instances = new CaseNoteStatus[9];
		instances[0] = ACTIVE;
		instances[1] = ARCHIVED;
		instances[2] = DESTROYED;
		instances[3] = MERGED;
		instances[4] = SCANNED;
		instances[5] = MARKED_AS_FOUND;
		instances[6] = MISSING;
		instances[7] = REQUIRES_MERGING;
		instances[8] = REQUIRES_CASE_NOTES;
		return instances;
	}
	public static String[] getNegativeInstanceNames()
	{
		String[] negativeInstances = new String[9];
		negativeInstances[0] = "ACTIVE";
		negativeInstances[1] = "ARCHIVED";
		negativeInstances[2] = "DESTROYED";
		negativeInstances[3] = "MERGED";
		negativeInstances[4] = "SCANNED";
		negativeInstances[5] = "MARKED_AS_FOUND";
		negativeInstances[6] = "MISSING";
		negativeInstances[7] = "REQUIRES_MERGING";
		negativeInstances[8] = "REQUIRES_CASE_NOTES";
		return negativeInstances;
	}
	public static CaseNoteStatus getNegativeInstance(String name)
	{
		if(name == null)
			return null;
		String[] negativeInstances = getNegativeInstanceNames();
		for (int i = 0; i < negativeInstances.length; i++)
		{
			if(negativeInstances[i].equals(name))
				return getNegativeInstances()[i];
		}
		return null;
	}
	public static CaseNoteStatus getNegativeInstance(Integer id)
	{
		if(id == null)
			return null;
		CaseNoteStatus[] negativeInstances = getNegativeInstances();
		for (int i = 0; i < negativeInstances.length; i++)
		{
			if(negativeInstances[i].getID() == id)
				return negativeInstances[i];
		}
		return null;
	}
	public int getTypeId()
	{
		return TYPE_ID;
	}
	public static final int TYPE_ID = 1021312;
	public static final CaseNoteStatus ACTIVE = new CaseNoteStatus(-2903, "Active", true, null, null, Color.Default);
	public static final CaseNoteStatus ARCHIVED = new CaseNoteStatus(-2904, "Archived", true, null, null, Color.Default);
	public static final CaseNoteStatus DESTROYED = new CaseNoteStatus(-2905, "Destroyed", true, null, null, Color.Default);
	public static final CaseNoteStatus MERGED = new CaseNoteStatus(-2911, "Merged", true, null, null, Color.Default);
	public static final CaseNoteStatus SCANNED = new CaseNoteStatus(-2920, "Scanned", true, null, null, Color.Default);
	public static final CaseNoteStatus MARKED_AS_FOUND = new CaseNoteStatus(-2933, "Found", true, null, null, Color.Default);
	public static final CaseNoteStatus MISSING = new CaseNoteStatus(-2934, "Missing", true, null, null, Color.Default);
	public static final CaseNoteStatus REQUIRES_MERGING = new CaseNoteStatus(-2938, "Requires Merging", true, null, null, Color.Default);
	public static final CaseNoteStatus REQUIRES_CASE_NOTES = new CaseNoteStatus(-2939, "Requires Case Notes", true, null, null, Color.Default);
}
