//#############################################################################
//#                                                                           #
//#  Copyright (C) <2014>  <IMS MAXIMS>                                       #
//#                                                                           #
//#  This program is free software: you can redistribute it and/or modify     #
//#  it under the terms of the GNU Affero General Public License as           #
//#  published by the Free Software Foundation, either version 3 of the       #
//#  License, or (at your option) any later version.                          # 
//#                                                                           #
//#  This program is distributed in the hope that it will be useful,          #
//#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#  GNU Affero General Public License for more details.                      #
//#                                                                           #
//#  You should have received a copy of the GNU Affero General Public License #
//#  along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
//#                                                                           #
//#############################################################################
//#EOH
// This code was generated by Barbara Worwood using IMS Development Environment (version 1.80 build 5007.25751)
// Copyright (C) 1995-2014 IMS MAXIMS. All rights reserved.
// WARNING: DO NOT MODIFY the content of this file

package ims.core.vo.beans;

public class VSArterialBloodGasBean extends ims.vo.ValueObjectBean
{
	public VSArterialBloodGasBean()
	{
	}
	public VSArterialBloodGasBean(ims.core.vo.VSArterialBloodGas vo)
	{
		this.id = vo.getBoId();
		this.version = vo.getBoVersion();
		this.ph = vo.getPH();
		this.paco2 = vo.getPaCO2();
		this.pao2 = vo.getPaO2();
		this.sbc = vo.getSBC();
		this.baseexcess = vo.getBaseExcess();
		this.ventilationmode = vo.getVentilationMode() == null ? null : (ims.vo.LookupInstanceBean)vo.getVentilationMode().getBean();
	}

	public void populate(ims.vo.ValueObjectBeanMap map, ims.core.vo.VSArterialBloodGas vo)
	{
		this.id = vo.getBoId();
		this.version = vo.getBoVersion();
		this.ph = vo.getPH();
		this.paco2 = vo.getPaCO2();
		this.pao2 = vo.getPaO2();
		this.sbc = vo.getSBC();
		this.baseexcess = vo.getBaseExcess();
		this.ventilationmode = vo.getVentilationMode() == null ? null : (ims.vo.LookupInstanceBean)vo.getVentilationMode().getBean();
	}

	public ims.core.vo.VSArterialBloodGas buildVo()
	{
		return this.buildVo(new ims.vo.ValueObjectBeanMap());
	}

	public ims.core.vo.VSArterialBloodGas buildVo(ims.vo.ValueObjectBeanMap map)
	{
		ims.core.vo.VSArterialBloodGas vo = null;
		if(map != null)
			vo = (ims.core.vo.VSArterialBloodGas)map.getValueObject(this);
		if(vo == null)
		{
			vo = new ims.core.vo.VSArterialBloodGas();
			map.addValueObject(this, vo);
			vo.populate(map, this);
		}
		return vo;
	}

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer value)
	{
		this.id = value;
	}
	public int getVersion()
	{
		return this.version;
	}
	public void setVersion(int value)
	{
		this.version = value;
	}
	public Float getPH()
	{
		return this.ph;
	}
	public void setPH(Float value)
	{
		this.ph = value;
	}
	public Float getPaCO2()
	{
		return this.paco2;
	}
	public void setPaCO2(Float value)
	{
		this.paco2 = value;
	}
	public Float getPaO2()
	{
		return this.pao2;
	}
	public void setPaO2(Float value)
	{
		this.pao2 = value;
	}
	public Float getSBC()
	{
		return this.sbc;
	}
	public void setSBC(Float value)
	{
		this.sbc = value;
	}
	public Float getBaseExcess()
	{
		return this.baseexcess;
	}
	public void setBaseExcess(Float value)
	{
		this.baseexcess = value;
	}
	public ims.vo.LookupInstanceBean getVentilationMode()
	{
		return this.ventilationmode;
	}
	public void setVentilationMode(ims.vo.LookupInstanceBean value)
	{
		this.ventilationmode = value;
	}

	private Integer id;
	private int version;
	private Float ph;
	private Float paco2;
	private Float pao2;
	private Float sbc;
	private Float baseexcess;
	private ims.vo.LookupInstanceBean ventilationmode;
}
